### ISSUE TITLE
"Extension server error: Operation failed: Permission denied"

### ISSUE THREAD

**Issue by b-smiley** [iPzard/electron-react-python-template#64]
# Electron app appears to be waiting for flask. Cannot get to the main page of the starter code.

Error Messages (They just kept repeating until I Ctrl+C)
---
yarn run start
yarn run v1.22.19
warning ..\..\..\..\package.json: No license field
$ node ./scripts/dispatch start

(node:21648) ExtensionLoadWarning: Warnings loading extension at C:\Users\smile\AppData\Roaming\electron-react-python-template\extensions\fmkadmapgofadopljbjfkapdkoienihi:
  Unrecognized manifest key 'action'.
  Unrecognized manifest key 'minimum_chrome_version'.
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\smile\repo\test\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\smile\repo\test\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\smile\repo\test\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\smile\repo\test\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\smile\repo\test\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\smile\repo\test\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\smile\repo\test\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\smile\repo\test\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\smile\repo\test\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\smile\repo\test\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\smile\repo\test\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.0
(node:21648) electron: Failed to load URL: http://localhost:3000/ with error: ERR_CONNECTION_RESET
[21648:0729/183828.732:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183828.732:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)   
[21648:0729/183829.735:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183830.746:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183831.745:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
(node:21648) electron: Failed to load URL: http://localhost:3000/ with error: ERR_CONNECTION_REFUSED
[21648:0729/183831.994:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183831.996:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
(node:21648) electron: Failed to load URL: http://localhost:3000/ with error: ERR_CONNECTION_REFUSED
[21648:0729/183832.308:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183832.316:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183832.740:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[21648:0729/183833.737:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/models/extensions/extensions.js (1)

**Steps to Reproduce**<br />
1. Followed the getting started guide
2. Git cloned, using Git bash
3. pip3 install -r requirements.txt
4. yarn install
5. yarn run start

**Expected behavior**<br />
I expect the main boilerplate app to load.

**Screenshots**<br />
![image](https://github.com/iPzard/electron-react-python-template/assets/66867383/3b4f37b8-7a4d-4735-8e7d-a4bbb4743ca1)

**Additional context**<br />
I set the Firewall on windows to allow both private and public networks, or either or. The issue persists in all scenarios

**Comment by msimoni18** [comment]
I've been using this template successfully for a while now. For some unknown reason I'm also getting these messages when trying to start my app, except I'm using ``Node.js v18.16.1``.

**Comment by AlexSkillman10** [comment]
having this issue as well

**Comment by TheNextGuy32** [comment]
I am experiencing this issue as well.

**Comment by tgourdel** [comment]
Experiencing the same

**Comment by alexandersvozil** [comment]
have the same issue on mac

**Comment by huangzhii** [comment]
The error message you're encountering `ERR_OSSL_EVP_UNSUPPORTED` is a common issue when using Node.js version 17 or newer with certain tools or dependencies that rely on OpenSSL for cryptographic functions.

My solution is to change the Node.js version. You can use a version manager such as nvm (Node Version Manager) for Unix-based systems (Linux, macOS) or nvm-windows for Windows. Here's how you would use nvm to switch to Node.js version 16:
```
nvm install 16
nvm use 16
```

After that, make sure to either close and reopen your terminal for the nvm command to become available, or you can source your profile file with a command like `source ~/.zshrc` (the file may vary based on your shell).

When open a new terminal, run `nvm use 16` again.

Then this issue will be disappear.

**Comment by nicholaswhite752** [comment]
https://github.com/iPzard/electron-react-python-template/blob/c78c0d0578bf6e6b0c96564fe7291ca6871d29ae/scripts/start.js#L33-L35

Another solution is to start the development script with the legacy ssl mode on line 34

`spawn('cross-env BROWSER=none NODE_OPTIONS=--openssl-legacy-provider react-scripts start', spawnOptions.showLogs);`
